[package]
name = "gst_pipeline_studio"
version = "0.2.2"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4.1", package = "gtk4" }
gst = { package = "gstreamer", version = "0.18.1" }
gst-plugin-gtk4 = { version = "0.1.1", optional=true }
anyhow = "1"
gettext-rs = {version = "0.7", features = ["gettext-system"]}
log = "0.4.11"
once_cell = "1.7.2"
xml-rs = "0.8.4"
x11 = { version = "2.18", features = ["xlib"] }
serde = "1.0"
serde_any = "0.5"
simplelog = "0.11.2"
futures-channel = "0.3"

[dev-dependencies]
futures-executor = "0.3"

[features]
default = ["gtk4-plugin"]
gtk4-plugin = ["gst-plugin-gtk4"]