[package]
name = "gst_pipeline_studio"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4.1", package = "gtk4" }
anyhow = "1"
gettext-rs = {version = "0.7", features = ["gettext-system"]}
gstreamer = "0.17"
log = "0.4.11"
once_cell = "1.7.2"
xml-rs = "0.8.4"
x11 = { version = "2.18", features = ["xlib"] }
serde = "1.0"
serde_any = "0.5"
simplelog = "0.11.2"